### ISSUE TITLE
seeder-job.yaml is missing tolerations

### ISSUE THREAD

**Issue by harrison-seow-develab** [opf/helm-charts#117]
## Issue
The `seeder-job.yaml` file is missing the `tolerations` configuration as compared to `web-deployment.yaml` or `worker-deployment.yaml`.

This causes the entire helm installation to fail when using `nodeSelector` if the node has `taints` as the seeder will be stuck in `pending` state.

## Workaround
1. Run `helm pull openproject --repo https://charts.openproject.org --destination ./chart`
2. Modify `seeder-job.yaml`
3. Install using local helm chart

## Fix
Please check [PR 116](https://github.com/opf/helm-charts/pull/116).

**Comment by oliverguenther** [comment]
Released as 5.4.0: https://github.com/opf/helm-charts/releases/tag/openproject-5.4.0
