### ISSUE TITLE
openproject-web init container gets OOM killed

### ISSUE THREAD

**Issue by jklare** [opf/helm-charts#136]
Hi,

after upgrading from 7.1.0 to 7.2.0, the openproject-web pod started to be stuck in a crashloop, since the init container itself was killed by the OOM Killer of the cluster. After looking at the changes, i identified the commit 3ff3f9510f63ce7202a1ca4b03bb8cf97074ed50 as the one, that broke it for me. I guess the limits that are now set for the init container are too small for it to run. After removing the newly set resources limit for the init container, everything got back into a working state. Without diving too deep into the code, i can't be sure what the expectations for the initContainer here are, so i can't give a more detailed recommendation on how to set the limit.

Cheers,
Jan

**Comment by oliverguenther** [comment]
Thanks @jklare for the issue. the `wait-for-db` triggers more than I expected it to, and loads the entire Rails env. With it, we need to change it to use the web/worker limits (something around ~4-500mb)

**Comment by oliverguenther** [comment]
To be published as 8.0.0 momentarily. Major because we renamed one value (initdb -> dbInit) for consistency.

**Comment by jklare** [comment]
Thanks a lot for addressing this so quickly. I upgraded to 8.0 with the given default resource limits and everything seems to start fine now.
