### ISSUE TITLE
IMAP credentials from secret

### ISSUE THREAD

**Issue by famfop** [opf/helm-charts#158]
Hi,
I am currently trying out the helm chart and am failing to understand the following:

Coming from a docker-compose setup, I am mostly customizing the `environment` hash as I was previously configuring the `.env` file. Among others, I am setting IMAP and would like to configure `IMAP_USERNAME` and `IMAP_PASSWORD` through the helm-chart.

Is it possible to pass the password from a secret using a `secretKeyRef`?

**Comment by machisuji** [comment]
Hi, the current helm setup actually doesn't cover the incoming emails feature at all. I've created a PR (#160) which adds this. It's almost complete. You can follow the PR to see when it's available.

**Comment by oliverguenther** [comment]
This is available in Helm chart 9.3.0 🎉
