### ISSUE TITLE
Memcached credentials not being used?

### ISSUE THREAD

**Issue by johanneskastl** [opf/helm-charts#18]
https://github.com/opf/helm-charts/blob/cd48e0650f2c3ab2551ac2b066599ff596f3153e/charts/openproject/values.yaml#L152

I found no use of the `.Values.memcached.auth.*` settings in any of the OpenProject related files. It might be used by the memcached chart, but what use is setting credentials only on one side of the connection?

Hence I guess those can be removed? Or if this charts assumes the default credentials (username and password both `memcached`, then this needs to be fixed.

**Comment by oliverguenther** [comment]
This has been removed in #46
