### ISSUE TITLE
The ingress class name uses nginx by default instead of the cluster default

### ISSUE THREAD

**Issue by fungiboletus** [opf/helm-charts#2]
Hei,

I think it would be better to use the cluster default ingress by default. Many kubernetes clusters don't use nginx.

https://github.com/opf/helm-charts/blob/908ebac1bf1ffa7c82ff7f52b33c7a66d9554713/charts/openproject/values.yaml#L47

**Comment by hanbinloop** [comment]
Yeah, I think so too
