### ISSUE TITLE
Use existingSecret for oidc secret as well

### ISSUE THREAD

**Issue by webnotesweb** [opf/helm-charts#63]
Hello,

I have noticed that you have done recently refactoring of secrets handling and improving secret management.
Thank you for that! I am referring for example to these: https://github.com/opf/helm-charts/pull/46 https://github.com/opf/helm-charts/issues/17

So this current "issue" might not be considered issue/bug but rather security enhancement suggestion if I may.

If possible, can you please enable use of `existingSecret` as well for [oidc secret](https://github.com/opf/helm-charts/blob/main/charts/openproject/values.yaml#L281) just as you have done with [PG](https://github.com/opf/helm-charts/blob/main/charts/openproject/templates/_helpers.tpl#L77) for example.

Thank you very much for your time and help!

**Comment by oliverguenther** [comment]
Thanks for your report, indeed this is a good use case for OIDC as well, and I'll submit a PR when I find the time. We welcome outside contributions as well
