### ISSUE TITLE
web deployment stuck in CrashLoopBackOff with new secret layout

### ISSUE THREAD

**Issue by DaDummy** [opf/helm-charts#78]
The current chart releases appear to be unable to deploy any OpenProject release I have tried so far, since there appears to be no release that actually supports omitting the password in the `DATABASE_URL` environment variable.

When the postgres password is not included in `DATABASE_URL`  as is the case with current chart versions, the web container fails to start because the `supervisord` script used for running the web container only uses `DATABASE_URL`  and ignores any values that might be set in `OPENPROJECT_DB_PASSWORD`.

I'd suggest rolling back to the old behavior until the OpenProject image officially supports this alternate approach.

**Comment by DaDummy** [comment]
Looks like additionally OpenProject web container does not support running as a different user than root, so

```
containerSecurityContext:
  enabled: false
```

should be the default for this chart until that changes.

**Comment by oliverguenther** [comment]
Hi @DaDummy , the `supervisord` command only exists for the all-in-one/fat docker images. The helm-chart should be used with the `-slim` variants. It's not properly documented I see, but it uses 13-slim as a default.

The slim container can also be run as non-root.
